apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: devflow-gateway
spec:
  selector:
    app: istio-ingress
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: bei-tls
    hosts:
    - "*"
